feat(vis): Prepare "Results prob lstm" plot; add geo specific models to receive geo data
Mosqlimate-project/Data-platform pull request #172
Opened 2024-03-06 17:31 UTC by luabida

2024-03-10 20:13 UTC, fccoelho commented on src/vis/api.py
> +        200: List[ResultsProbLSTMSchema],
For now it is ok, But using a specific model type (LSTM) for the API endpoint is not  a good Idea.

2024-03-10 20:17 UTC, fccoelho approved these changes

2024-03-11 12:20 UTC, luabida commented on src/vis/api.py
> +        200: List[ResultsProbLSTMSchema],
I don't think I get what you meant, the ResultsProbLSTMSchema is the json parser for the django-ninja to insert into the ResultsProbLSTM model or return it in the API

2024-03-11 13:06 UTC, fccoelho commented on src/vis/schema.py
> +    macroregion: int
change `macroregion` to `geocode`

2024-03-11 13:11 UTC, fccoelho requested changes

2024-03-11 13:11 UTC, fccoelho commented on src/vis/schema.py
> +    HT: float
change `HT` to `high_threshold`

2024-03-11 13:11 UTC, fccoelho commented on src/vis/schema.py
> +    LT: float
change `LT` to `low_threshold`

2024-03-11 13:11 UTC, fccoelho commented on src/vis/schema.py
> +    HTinc: float
change `HTinc` to `high_inc_threshold` ou `high_incidence_threshold`.

2024-03-11 13:11 UTC, fccoelho commented on src/vis/schema.py
> +    LTinc: float
do as done for `HTinc`

2024-03-11 15:14 UTC, eduardocorrearaujo approved these changes

2024-03-11 16:05 UTC, fccoelho approved these changes

2024-03-11 16:16 UTC, merged