chore(structure): create initial django structure
Mosqlimate-project/Data-platform pull request #3
Opened 2023-05-25 17:57 UTC by luabida

2023-05-25 17:58 UTC, luabida commented
@fccoelho what do you think the structure should be?

current:
```
src/
├── manage.py
└── mosqclimate
    ├── asgi.py
    ├── __init__.py
    ├── __pycache__
    │   ├── __init__.cpython-311.pyc
    │   ├── settings.cpython-311.pyc
    │   └── urls.cpython-311.pyc
    ├── settings.py
    ├── urls.py
    └── wsgi.py
   ```

2023-05-25 19:02 UTC, fccoelho commented
That's correct, but after that, the tutorial recommends running a `./manage.py startapp <app_name>`

2023-05-25 19:06 UTC, fccoelho commented
I don't usually put everything under `src/` I tend to follow the structure recommended by the docs, and created with the `startproject` command.

2023-05-25 19:13 UTC, fccoelho requested changes

2023-05-25 19:13 UTC, fccoelho commented on pyproject.toml
> +name = "mosqclimate-data"
it's "mosqliamate" without the "c"

2023-05-25 19:13 UTC, fccoelho commented on src/mosqclimate/asgi.py
> +os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mosqclimate.settings')
replace "mosqclimate" by "mosqlimate" everywhere

2023-05-25 20:13 UTC, luabida commented
> That's correct, but after that, the tutorial recommends running a `./manage.py startapp <app_name>`

I think it would be good to discuss the design of the project, as the apps, the backend integration with postgres, models, containerization etc..

2023-05-29 15:01 UTC, fccoelho commented
I suggest we have two apps in the project:

- datastore: this will give access to data on Epigraphhub and Infodengue. Basically a get only API wrapping external databases
- registry: This is a model registry with three tables:
  - Author: table containing the following columns: `name (varchar), email (email), institution (varchar)
  - Model: should contain the following columns: `name (varchar),  author (author id), repository (url), implementation_language (varchar), type (varchar)
  - Predictions: should contain at least the following columns: `model (model id), commit (commit id of the version used), predict_date (datetime), prediction (JSON)

2023-05-31 00:21 UTC, luabida commented
This PR is getting too big. I've finished the API for the `registry` app and its endpoints.

How to test it:
- set .env vars (require postgres. currently accepting only external postgres connections)
- run `python src/manage.py runserver`
- access `http://127.0.0.1:8000/api/docs` to test the API requests

2023-05-31 14:06 UTC, fccoelho approved these changes

2023-06-06 11:33 UTC, merged